#!/usr/bin/env python

import pycturetube
from optparse import OptionParser

if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option("-c", "--cols", default=80, type="int", dest="cols",
                      help="Set the columns to print")

    (options, args) = parser.parse_args()

    if len(args) >= 1:
        for i in args:
            print pycturetube.renderify(i, options.cols)